CATEGORIES = [
    "Recebimentos",
    "Adicionais",
    "A",
    "B",
    "C",
    "D",
    "Livros",
    "Inglês",
    "Curso",
    "Produtos Saúde",
    "Psicóloga",
    "Alimentação",
    "Aluguel",
    "Internet",
    "Celular",
    "Ajuda Casa",
    "Utilidade Casa",
    "Pet",
    "Higiene Pessoal",
    "Barbearia",
    "Esporte",
    "Vestimenta",
    "Restaurante",
    "Viagem",
    "Ferramentas",
    "Eletrônico",
    "Outros",
    "Combustível",
    "Estacionamento",
    "Lavagem",
    "Seguro",
    "Impostos Auto",
    "Financiamento",
    "Empréstimos",
    "Multas",
    "Manutenção",
    "Locomoção",
    "Impostos",
    "Necessários",
    "Opcionais",
    "Presentes",
    "Planos",
    "Assinatura",
    "Doações",
    "Exterior",
]
